export default data = [
   {
      state: 'Afghanistan',
      capital: 'Kaboul',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Albanie',
      capital: 'Tirana',
      niveau : 3,
      continent: 'Europe',
   },
   {
      state: 'Algérie',
      capital: 'Alger',
      niveau : 0,
      continent: 'Afrique',
   },
   {
      state: 'Andorre',
      capital: 'Andorre La Vella',
      niveau : 4,
      continent: 'Europe',
   },
   {
      state: 'Angola',
      capital: 'Luanda',
      niveau : 10,
      continent: 'Afrique',
   },
   {
      state: 'Anguilla',
      capital: 'The Valley',
      niveau : 10,
      continent: 'Ameriques',
   },
   {
      state: 'Antigua et Barbuda',
      capital: 'Saint-Jean',
      niveau : 10,
      continent: 'Ameriques',
   },
   {
      state: 'Argentine',
      capital: 'Buenos Aires',
      niveau : 0,
      continent: 'Ameriques',
   },
   {
      state: 'Arménie',
      capital: 'Erevan',
      niveau : 3,
      continent: 'Europe',
   },
   {
      state: 'Aruba',
      capital: 'Oranjestad',
      niveau : 10,
      continent: 'Ameriques',
   },
   {
      state: 'Australie',
      capital: 'Canberra',
      niveau : 1,
      continent: 'AsiePacif',
   },
   {
      state: 'Autriche',
      capital: 'Vienne',
      niveau : 1,
      continent: 'Europe',
   },
   {
      state: 'Azerbaïdjan',
      capital: 'Bakou',
      niveau : 10,
      continent: 'Europe',
   },
   {
      state: 'Iles des Açores',
      capital: 'Ponta Delgada',
      niveau : 10,
      continent: 'Europe',
   },
   {
      state: 'Bahamas',
      capital: 'Nassau',
      niveau : 2,
      continent: 'Ameriques',
   },
   {
      state: 'Bahreïn',
      capital: 'Manama',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Bangladesh',
      capital: 'Dhaka',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Barbade',
      capital: 'Bridgetown',
      niveau : 10,
      continent: 'Ameriques',
   },
   {
      state: 'Belgique',
      capital: 'Bruxelles',
      niveau : 0,
      continent: 'Europe',
   },
   {
      state: 'Bélize',
      capital: 'Belmopan',
      niveau : 10,
      continent: 'Ameriques',
   },
   {
      state: 'Bénin',
      capital: 'Porto Novo',
      niveau : 10,
      continent: 'Afrique',
   },
   {
      state: 'Iles Bermudes',
      capital: 'Hamilton',
      niveau : 10,
      continent: 'Ameriques',
   },
   {
      state: 'Bhoutan',
      capital: 'Thimbou',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Bolivie',
      capital: 'La Paz',
      niveau : 10,
      continent: 'Ameriques',
   },
   {
      state: 'Bosnie-Herzégovine',
      capital: 'Sarajevo',
      niveau : 10,
      continent: 'Europe',
   },
   {
      state: 'Botswana',
      capital: 'Gaborone',
      niveau : 10,
      continent: 'Afrique',
   },
   {
      state: 'Brésil',
      capital: 'Brasilia',
      niveau : 0,
      continent: 'Ameriques',
   },
   {
      state: 'Iles Vierges Britanniques',
      capital: 'Road Town',
      niveau : 10,
      continent: 'Ameriques',
   },
   {
      state: 'Bulgarie',
      capital: 'Sofia',
      niveau : 10,
      continent: 'Europe',
   },
   {
      state: 'Burkina Faso',
      capital: 'Ouagadougou',
      niveau : 10,
      continent: 'Afrique',
   },
   {
      state: 'Burundi',
      capital: 'Bujumbura',
      niveau : 10,
      continent: 'Afrique',
   },
   {
      state: 'Cambodge',
      capital: 'Phnom Penh',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Cameroun',
      capital: 'Yaoundé',
      niveau : 1,
      continent: 'Afrique',
   },
   {
      state: 'Canada',
      capital: 'Ottawa',
      niveau : 10,
      continent: 'Ameriques',
   },
   {
      state: 'Cap Vert',
      capital: 'Praïa',
      niveau : 10,
      continent: 'Afrique',
   },
   {
      state: 'Iles Cayman',
      capital: 'Georgetown',
      niveau : 10,
      continent: 'Ameriques',
   },
   {
      state: 'Centre-Afrique',
      capital: 'Bangui',
      niveau : 10,
      continent: 'Afrique',
   },
   {
      state: 'Tchad',
      capital: 'N Djamena',
      niveau : 3,
      continent: 'Afrique',
   },
   {
      state: 'Chili',
      capital: 'Santiago',
      niveau : 0,
      continent: 'Ameriques',
   },
   {
      state: 'Chine',
      capital: 'Pékin',
      niveau : 0,
      continent: 'AsiePacif',
   },
   {
      state: 'Colombie',
      capital: 'Bogota',
      niveau : 10,
      continent: 'Ameriques',
   },
   {
      state: 'Comoros',
      capital: 'Moroni',
      niveau : 10,
      continent: 'Afrique',
   },
   {
      state: 'Congo',
      capital: 'Brazzaville',
      niveau : 1,
      continent: 'Afrique',
   },
   {
      state: 'Iles Cook',
      capital: 'Avarua',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Costa Rica',
      capital: 'San José',
      niveau : 10,
      continent: 'Ameriques',
   },
   {
      state: 'Croatie',
      capital: 'Zagreb',
      niveau : 3,
      continent: 'Europe',
   },
   {
      state: 'Cuba',
      capital: 'La Havane',
      niveau : 1,
      continent: 'Ameriques',
   },
   {
      state: 'Chypre',
      capital: 'Nicosie',
      niveau : 4,
      continent: 'Europe',
   },
   {
      state: 'République Tchèque',
      capital: 'Prague',
      niveau : 2,
      continent: 'Europe',
   },
   {
      state: 'Danemark',
      capital: 'Copenhage',
      niveau : 2,
      continent: 'Europe',
   },
   {
      state: 'Djibouti',
      capital: 'Djibouti',
      niveau : 0,
      continent: 'Afrique',
   },
   {
      state: 'Dominique',
      capital: 'Roseau',
      niveau : 10,
      continent: 'Ameriques',
   },
   {
      state: 'République Dominicaine',
      capital: 'Saint-Domingue',
      niveau : 10,
      continent: 'Ameriques',
   },
   {
      state: 'Equateur',
      capital: 'Quito',
      niveau : 2,
      continent: 'Ameriques',
   },
   {
      state: 'Egypte',
      capital: 'Le Caire',
      niveau : 0,
      continent: 'Afrique',
   },
   {
      state: 'El Salvador',
      capital: 'San Salvador',
      niveau : 10,
      continent: 'Ameriques',
   },
   {
      state: 'Guinée Equatoriale',
      capital: 'Malabo',
      niveau : 10,
      continent: 'Afrique',
   },
   {
      state: 'Erythrée',
      capital: 'Asmera',
      niveau : 10,
      continent: 'Afrique',
   },
   {
      state: 'Estonie',
      capital: 'Tallinn',
      niveau : 10,
      continent: 'Europe',
   },
   {
      state: 'Ethiopie',
      capital: 'Addis-Abéba',
      niveau : 10,
      continent: 'Afrique',
   },
   {
      state: 'Iles Falkland',
      capital: 'Stanley',
      niveau : 10,
      continent: 'Ameriques',
   },
   {
      state: 'Fidji',
      capital: 'Suva',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Finlande',
      capital: 'Helsinki',
      niveau : 10,
      continent: 'Europe',
   },
   {
      state: 'Macédoine',
      capital: 'Skopje',
      niveau : 10,
      continent: 'Europe',
   },
   {
      state: 'France',
      capital: 'Paris',
      niveau : 0,
      continent: 'Europe',
   },
   {
      state: 'Guyane Française',
      capital: 'Cayenne',
      niveau : 10,
      continent: 'Ameriques',
   },
   {
      state: 'Polynésie Française',
      capital: 'Papeete',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Gabon',
      capital: 'Libreville',
      niveau : 2,
      continent: 'Afrique',
   },
   {
      state: 'Gambie',
      capital: 'Banjul',
      niveau : 10,
      continent: 'Afrique',
   },
   {
      state: 'Georgie',
      capital: 'Tbilissi',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Allemagne',
      capital: 'Berlin',
      niveau : 0,
      continent: 'Europe',
   },
   {
      state: 'Ghana',
      capital: 'Accra',
      niveau : 10,
      continent: 'Afrique',
   },
   {
      state: 'Gibraltar',
      capital: 'Gibraltar',
      niveau : 1,
      continent: 'Europe',
   },
   {
      state: 'Grèce',
      capital: 'Athènes',
      niveau : 1,
      continent: 'Europe',
   },
   {
      state: 'Groenland',
      capital: 'Nuuk',
      niveau : 10,
      continent: 'Europe',
   },
   {
      state: 'Grenade',
      capital: 'Saint-George',
      niveau : 10,
      continent: 'Ameriques',
   },
   {
      state: 'Guadeloupe',
      capital: 'Basse-Terre',
      niveau : 10,
      continent: 'Ameriques',
   },
   {
      state: 'Guam',
      capital: 'Agana',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Guatémala',
      capital: 'Guatémala',
      niveau : 2,
      continent: 'Ameriques',
   },
   {
      state: 'Guinée',
      capital: 'Conakry',
      niveau : 3,
      continent: 'Afrique',
   },
   {
      state: 'Guinée Bissau',
      capital: 'Bissao',
      niveau : 10,
      continent: 'Afrique',
   },
   {
      state: 'Guyana',
      capital: 'Georgetown',
      niveau : 10,
      continent: 'Ameriques',
   },
   {
      state: 'Haïti',
      capital: 'Port-au-Prince',
      niveau : 10,
      continent: 'Ameriques',
   },
   {
      state: 'Honduras',
      capital: 'Tegucigalpa',
      niveau : 3,
      continent: 'Ameriques',
   },
   {
      state: 'Hongrie',
      capital: 'Budapest',
      niveau : 3,
      continent: 'Europe',
   },
   {
      state: 'Islande',
      capital: 'Reykjavik',
      niveau : 10,
      continent: 'Europe',
   },
   {
      state: 'Inde',
      capital: 'New Delhi',
      niveau : 1,
      continent: 'AsiePacif',
   },
   {
      state: 'Indonésie',
      capital: 'Jakarta',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Iran',
      capital: 'Téhéran',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Irak',
      capital: 'Bagdad',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Irlande',
      capital: 'Dublin',
      niveau : 1,
      continent: 'Europe',
   },
   {
      state: 'Israël',
      capital: 'Jérusalem',
      niveau : 1,
      continent: 'AsiePacif',
   },
   {
      state: 'Italie',
      capital: 'Rome',
      niveau : 0,
      continent: 'Europe',
   },
   {
      state: 'Côte d Ivoire',
      capital: 'Abidjan',
      niveau : 1,
      continent: 'Afrique',
   },
   {
      state: 'Jamaïque',
      capital: 'Kingston',
      niveau : 10,
      continent: 'Ameriques',
   },
   {
      state: 'Japon',
      capital: 'Tokyo',
      niveau : 0,
      continent: 'AsiePacif',
   },
   {
      state: 'Jordanie',
      capital: 'Amman',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Kazakhstan',
      capital: 'Alma-Ata',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Kénya',
      capital: 'Nairobi',
      niveau : 2,
      continent: 'Afrique',
   },
   {
      state: 'Kiribati',
      capital: 'Tarawa',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Corée du Nord',
      capital: 'Pyongyang',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Corée du Sud',
      capital: 'Séoul',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Koweït',
      capital: 'Koweït',
      niveau : 2,
      continent: 'AsiePacif',
   },
   {
      state: 'Kirghizstan',
      capital: 'Bichkek',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Laos',
      capital: 'Vientiane',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Lettonie',
      capital: 'Riga',
      niveau : 4,
      continent: 'Europe',
   },
   {
      state: 'Liban',
      capital: 'Beyrouth',
      niveau : 2,
      continent: 'AsiePacif',
   },
   {
      state: 'Lésotho',
      capital: 'Maseru',
      niveau : 10,
      continent: 'Afrique',
   },
   {
      state: 'Libéria',
      capital: 'Monrovia',
      niveau : 10,
      continent: 'Afrique',
   },
   {
      state: 'Libye',
      capital: 'Tripoli',
      niveau : 1,
      continent: 'Afrique',
   },
   {
      state: 'Liechtenstein',
      capital: 'Vaduz',
      niveau : 10,
      continent: 'Europe',
   },
   {
      state: 'Lituanie',
      capital: 'Vilnius',
      niveau : 4,
      continent: 'Europe',
   },
   {
      state: 'Luxembourg',
      capital: 'Luxembourg',
      niveau : 0,
      continent: 'Europe',
   },
   {
      state: 'Madagascar',
      capital: 'Antananarivo',
      niveau : 3,
      continent: 'Afrique',
   },
   {
      state: 'Malawi',
      capital: 'Lilongwé',
      niveau : 10,
      continent: 'Afrique',
   },
   {
      state: 'Malaisie',
      capital: 'Kuala Lumpur',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Maldives',
      capital: 'Male',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Mali',
      capital: 'Bamako',
      niveau : 2,
      continent: 'Afrique',
   },
   {
      state: 'Malte',
      capital: 'La Vallette',
      niveau : 10,
      continent: 'Europe',
   },
   {
      state: 'Iles Marshall',
      capital: 'Majuro',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Martinique',
      capital: 'Fort-de-France',
      niveau : 10,
      continent: 'Ameriques',
   },
   {
      state: 'Mauritanie',
      capital: 'Nouakchott',
      niveau : 10,
      continent: 'Afrique',
   },
   {
      state: 'Maurice',
      capital: 'Port-Louis',
      niveau : 10,
      continent: 'Afrique',
   },
   {
      state: 'Mexique',
      capital: 'Mexico',
      niveau : 0,
      continent: 'Ameriques',
   },
   {
      state: 'Moldavie',
      capital: 'Chisinau',
      niveau : 10,
      continent: 'Europe',
   },
   {
      state: 'Monaco',
      capital: 'Monaco',
      niveau : 3,
      continent: 'Europe',
   },
   {
      state: 'Mongolie',
      capital: 'Oulan-Bator',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Maroc',
      capital: 'Rabat',
      niveau : 1,
      continent: 'Afrique',
   },
   {
      state: 'Mozambique',
      capital: 'Maputo',
      niveau : 10,
      continent: 'Afrique',
   },
   {
      state: 'Myanmar',
      capital: 'Rangoon',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Namibie',
      capital: 'Windhoek',
      niveau : 3,
      continent: 'Afrique',
   },
   {
      state: 'Nauru',
      capital: 'Yaren',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Népal',
      capital: 'Katmandou',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Pays-Bas',
      capital: 'Amsterdam',
      niveau : 1,
      continent: 'Europe',
   },
   {
      state: 'Nouvelle Calédonie',
      capital: 'Nouméa',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Nouvelle Zélande',
      capital: 'Wellington',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Nicaragua',
      capital: 'Managua',
      niveau : 10,
      continent: 'Ameriques',
   },
   {
      state: 'Niger',
      capital: 'Niamey',
      niveau : 10,
      continent: 'Afrique',
   },
   {
      state: 'Nigéria',
      capital: 'Lagos',
      niveau : 4,
      continent: 'Afrique',
   },
   {
      state: 'Niue',
      capital: 'Alofi',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Iles Mariannes du Nord',
      capital: 'Capitol Hill',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Norvège',
      capital: 'Oslo',
      niveau : 2,
      continent: 'Europe',
   },
   {
      state: 'Oman',
      capital: 'Mascate',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Pakistan',
      capital: 'Islamabad',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Iles Palau',
      capital: 'Koror',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Panama',
      capital: 'Panama',
      niveau : 0,
      continent: 'Ameriques',
   },
   {
      state: 'Papouasie-Nouvelle-Guinée',
      capital: 'Port Moresby',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Paraguay',
      capital: 'Asuncion',
      niveau : 10,
      continent: 'Ameriques',
   },
   {
      state: 'Pérou',
      capital: 'Lima',
      niveau : 1,
      continent: 'Ameriques',
   },
   {
      state: 'Philippines',
      capital: 'Manille',
      niveau : 3,
      continent: 'AsiePacif',
   },
   {
      state: 'Portugal',
      capital: 'Lisbonne',
      niveau : 1,
      continent: 'Europe',
   },
   {
      state: 'Porto Rico',
      capital: 'San Juan',
      niveau : 10,
      continent: 'Ameriques',
   },
   {
      state: 'Qatar',
      capital: 'Doha',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Réunion',
      capital: 'Saint-Denis',
      niveau : 10,
      continent: 'Afrique',
   },
   {
      state: 'Roumanie',
      capital: 'Bucarest',
      niveau : 10,
      continent: 'Europe',
   },
   {
      state: 'Russie',
      capital: 'Moscou',
      niveau : 0,
      continent: 'AsiePacif',
   },
   {
      state: 'Rwanda',
      capital: 'Kigali',
      niveau : 5,
      continent: 'Afrique',
   },
   {
      state: 'Sainte-Lucie',
      capital: 'Castries',
      niveau : 10,
      continent: 'Ameriques',
   },
   {
      state: 'Saint-Marin',
      capital: 'Saint-Marin',
      niveau : 10,
      continent: 'Europe',
   },
   {
      state: 'Sao Tomé',
      capital: 'Sao Tomé',
      niveau : 10,
      continent: 'Afrique',
   },
   {
      state: 'Arabie Saoudite',
      capital: 'Riyad',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Sénégal',
      capital: 'Dakar',
      niveau : 0,
      continent: 'Afrique',
   },
   {
      state: 'Seychelles',
      capital: 'Victoria',
      niveau : 10,
      continent: 'Afrique',
   },
   {
      state: 'Sierra Léone',
      capital: 'Freetown',
      niveau : 10,
      continent: 'Afrique',
   },
   {
      state: 'Singapour',
      capital: 'Singapour',
      niveau : 1,
      continent: 'AsiePacif',
   },
   {
      state: 'Slovaquie',
      capital: 'Bratislava',
      niveau : 5,
      continent: 'Europe',
   },
   {
      state: 'Slovénie',
      capital: 'Ljubljana',
      niveau : 3,
      continent: 'Europe',
   },
   {
      state: 'Iles Salomon',
      capital: 'Honiara',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Somalie',
      capital: 'Mogadiscio',
      niveau : 4,
      continent: 'Afrique',
   },
   {
      state: 'Afrique du sud',
      capital: 'Prétoria',
      niveau : 10,
      continent: 'Afrique',
   },
   {
      state: 'Espagne',
      capital: 'Madrid',
      niveau : 0,
      continent: 'Europe',
   },
   {
      state: 'Sri Lanka',
      capital: 'Colombo',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Saint Kitts et Nevis',
      capital: 'Basse Terre',
      niveau : 10,
      continent: 'Ameriques',
   },
   {
      state: 'Saint-Vincent',
      capital: 'Kingstown',
      niveau : 10,
      continent: 'Ameriques',
   },
   {
      state: 'Soudan',
      capital: 'Khartoum',
      niveau : 3,
      continent: 'Afrique',
   },
   {
      state: 'Surinam',
      capital: 'Paramaribo',
      niveau : 10,
      continent: 'Ameriques',
   },
   {
      state: 'Swaziland',
      capital: 'Mbabane',
      niveau : 10,
      continent: 'Afrique',
   },
   {
      state: 'Suède',
      capital: 'Stockholm',
      niveau : 2,
      continent: 'Europe',
   },
   {
      state: 'Suisse',
      capital: 'Berne',
      niveau : 0,
      continent: 'Europe',
   },
   {
      state: 'Syrie',
      capital: 'Damas',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Taïwan',
      capital: 'Taipei',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Tadjikistan',
      capital: 'Douchanbé',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Tanzanie',
      capital: 'Dodoma',
      niveau : 10,
      continent: 'Afrique',
   },
   {
      state: 'Thaïlande',
      capital: 'Bangkok',
      niveau : 2,
      continent: 'AsiePacif',
   },
   {
      state: 'Togo',
      capital: 'Lomé',
      niveau : 10,
      continent: 'Afrique',
   },
   {
      state: 'Tonga',
      capital: 'Nuku Alofa',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Trinidad et Tobago',
      capital: 'Port d Espagne',
      niveau : 10,
      continent: 'Ameriques',
   },
   {
      state: 'Tunisie',
      capital: 'Tunis',
      niveau : 0,
      continent: 'Afrique',
   },
   {
      state: 'Turquie',
      capital: 'Ankara',
      niveau : 2,
      continent: 'Europe',
   },
   {
      state: 'Turkménistan',
      capital: 'Achkhabad',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Turks et Caicos',
      capital: 'Grand Turk',
      niveau : 10,
      continent: 'Ameriques',
   },
   {
      state: 'Tuvalu',
      capital: 'Funafuti',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Ouganda',
      capital: 'Kampala',
      niveau : 10,
      continent: 'Afrique',
   },
   {
      state: 'Ukraine',
      capital: 'Kiev',
      niveau : 5,
      continent: 'Europe',
   },
   {
      state: 'Emirats arabes unis',
      capital: 'Abu Dhabi',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Royaume-Uni',
      capital: 'Londres',
      niveau : 0,
      continent: 'Europe',
   },
   {
      state: 'Etats-Unis',
      capital: 'Washington',
      niveau : 0,
      continent: 'Ameriques',
   },
   {
      state: 'Uruguay',
      capital: 'Montevideo',
      niveau : 1,
      continent: 'Ameriques',
   },
   {
      state: 'Ouzbékistan',
      capital: 'Tachkent',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Vanuatu',
      capital: 'Port-Vila',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Vatican',
      capital: 'Vatican',
      niveau : 3,
      continent: 'Europe',
   },
   {
      state: 'Vénézuela',
      capital: 'Caracas',
      niveau : 1,
      continent: 'Ameriques',
   },
   {
      state: 'Vietnam',
      capital: 'Hanoi',
      niveau : 2,
      continent: 'AsiePacif',
   },
   {
      state: 'Samoa Orientale',
      capital: 'Apia',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Yemen',
      capital: 'Sanaa',
      niveau : 10,
      continent: 'AsiePacif',
   },
   {
      state: 'Serbie',
      capital: 'Belgrade',
      niveau : 5,
      continent: 'Europe',
   },
   {
      state: 'République démocratique du Congo',
      capital: 'Kinshasa',
      niveau : 3,
      continent: 'Afrique',
   },
   {
      state: 'Zambie',
      capital: 'Lusaka',
      niveau : 10,
      continent: 'Afrique',
   },
   {
      state: 'Zimbabwé',
      capital: 'Hararé',
      niveau : 10,
      continent: 'Afrique',
   },
   {
      state: 'Pologne',
      capital: 'Varsovie',
      niveau : 1,
      continent: 'Europe',
   },
   {
      state: 'Biélorussie',
      capital: 'Minsk',
      niveau : 5,
      continent: 'Europe',
   },
]