export default data = [
   {
      state: 'Croatie',
      prefixe: 'de la',
      capital: 'Zagreb',
      niveau : 5,
      continent: 'Europe',
      image: require('../Helpers/capital_images/zagreb.jpeg'),
   },
   {
      state: 'Nauru',
      prefixe: 'de',
      capital: 'Yaren',
      niveau : 10,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/yaren.jpeg'),
   },
   {
      state: 'Cameroun',
      prefixe: 'du',
      capital: 'Yaoundé',
      niveau : 6,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/yaounde.jpeg'),
   },
   {
      state: 'Namibie',
      prefixe: 'de la',
      capital: 'Windhoek',
      niveau : 7,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/windhoek.jpeg'),
   },
   {
      state: 'Nouvelle Zélande',
      prefixe: 'de la',
      capital: 'Wellington',
      niveau : 5,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/wellington.jpeg'),
   },
   {
      state: 'Etats-Unis',
      prefixe: 'des',
      capital: 'Washington',
      niveau : 0,
      continent: 'Ameriques',
      image: require('../Helpers/capital_images/washington.jpeg'),
   },
   {
      state: 'Lituanie',
      prefixe: 'de la',
      capital: 'Vilnius',
      niveau : 6,
      continent: 'Europe',
      image: require('../Helpers/capital_images/vilnius.jpeg'),
   },
   {
      state: 'Laos',
      prefixe: 'du',
      capital: 'Vientiane',
      niveau : 7,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/vientiane.jpeg'),
   },
   {
      state: 'Autriche',
      prefixe: 'de l’',
      capital: 'Vienne',
      niveau : 2,
      continent: 'Europe',
      image: require('../Helpers/capital_images/vienne.jpeg'),
   },
   {
      state: 'Seychelles',
      prefixe: 'des',
      capital: 'Victoria',
      niveau : 10,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/victoria.jpeg'),
   },
   {
      state: 'Pologne',
      prefixe: 'de la',
      capital: 'Varsovie',
      niveau : 2,
      continent: 'Europe',
      image: require('../Helpers/capital_images/varsovie.jpeg'),
   },
   {
      state: 'Liechtenstein',
      prefixe: 'du',
      capital: 'Vaduz',
      niveau : 7,
      continent: 'Europe',
      image: require('../Helpers/capital_images/vaduz.jpeg'),
   },
   {
      state: 'Tunisie',
      prefixe: 'de la',
      capital: 'Tunis',
      niveau : 0,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/tunis.jpeg'),
   },
   {
      state: 'Libye',
      prefixe: 'de la',
      capital: 'Tripoli',
      niveau : 4,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/tripoli.jpeg'),
   },
   {
      state: 'Japon',
      prefixe: 'du',
      capital: 'Tokyo',
      niveau : 1,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/tokyo.jpeg'),
   },
   {
      state: 'Albanie',
      prefixe: 'de l’',
      capital: 'Tirana',
      niveau : 4,
      continent: 'Europe',
      image: require('../Helpers/capital_images/tirana.jpeg'),
   },
   {
      state: 'Bhoutan',
      prefixe: 'du',
      capital: 'Thimbou',
      niveau : 10,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/thimbou.jpeg'),
   },
   {
      state: 'Iran',
      prefixe: 'de l’',
      capital: 'Téhéran',
      niveau : 4,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/teheran.jpeg'),
   },
   {
      state: 'Honduras',
      prefixe: 'du',
      capital: 'Tegucigalpa',
      niveau : 4,
      continent: 'Ameriques',
      image: require('../Helpers/capital_images/tegucigalpa.jpeg'),
   },
   {
      state: 'Georgie',
      prefixe: 'de la',
      capital: 'Tbilissi',
      niveau : 9,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/tbilissi.jpeg'),
   },
   {
      state: 'Estonie',
      prefixe: 'de l’',
      capital: 'Tallinn',
      niveau : 6,
      continent: 'Europe',
      image: require('../Helpers/capital_images/tallinn.jpeg'),
   },
   {
      state: 'Taïwan',
      prefixe: 'de',
      capital: 'Taipei',
      niveau : 7,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/taipei.jpeg'),
   },
   {
      state: 'Ouzbékistan',
      prefixe: 'de l’',
      capital: 'Tachkent',
      niveau : 8,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/tachkent.jpeg'),
   },
   {
      state: 'Fidji',
      prefixe: 'de',
      capital: 'Suva',
      niveau : 10,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/suva.jpeg'),
   },
   {
      state: 'Suède',
      prefixe: 'de la',
      capital: 'Stockholm',
      niveau : 2,
      continent: 'Europe',
      image: require('../Helpers/capital_images/stockholm.jpeg'),
   },
   {
      state: 'Bulgarie',
      prefixe: 'de la',
      capital: 'Sofia',
      niveau : 7,
      continent: 'Europe',
      image: require('../Helpers/capital_images/sofia.jpeg'),
   },
   {
      state: 'Macédoine',
      prefixe: 'de la',
      capital: 'Skopje',
      niveau : 9,
      continent: 'Europe',
      image: require('../Helpers/capital_images/skopje.jpeg'),
   },
   {
      state: 'Singapour',
      prefixe: 'de',
      capital: 'Singapour',
      niveau : 3,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/singapour.jpeg'),
   },
   {
      state: 'Corée du Sud',
      prefixe: 'de la',
      capital: 'Séoul',
      niveau : 4,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/seoul.jpeg'),
   },
   {
      state: 'Bosnie-Herzégovine',
      prefixe: 'de la',
      capital: 'Sarajevo',
      niveau : 8,
      continent: 'Europe',
      image: require('../Helpers/capital_images/sarajevo.jpeg'),
   },
   {
      state: 'Sao Tomé',
      prefixe: 'de',
      capital: 'Sao Tomé',
      niveau : 10,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/sao_tome.jpeg'),
   },
   {
      state: 'Chili',
      prefixe: 'du',
      capital: 'Santiago',
      niveau : 4,
      continent: 'Ameriques',
      image: require('../Helpers/capital_images/santiago.jpeg'),
   },
   {
      state: 'Yemen',
      prefixe: 'du',
      capital: 'Sanaa',
      niveau : 9,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/sanaa.jpeg'),
   },
   {
      state: 'El Salvador',
      prefixe: 'd’',
      capital: 'San Salvador',
      niveau : 6,
      continent: 'Ameriques',
      image: require('../Helpers/capital_images/san_salvador.jpeg'),
   },
   {
      state: 'Porto Rico',
      prefixe: 'de',
      capital: 'San Juan',
      niveau : 8,
      continent: 'Ameriques',
      image: require('../Helpers/capital_images/san_juan.jpeg'),
   },
   {
      state: 'Costa Rica',
      prefixe: 'de',
      capital: 'San José',
      niveau : 7,
      continent: 'Ameriques',
      image: require('../Helpers/capital_images/san_jose.jpeg'),
   },
   {
      state: 'Grenade',
      prefixe: 'de',
      capital: 'Saint-George',
      niveau : 10,
      continent: 'Ameriques',
      image: require('../Helpers/capital_images/saint-george.jpeg'),
   },
   {
      state: 'Rép. Dominicaine',
      prefixe: 'de la',
      capital: 'Saint-Domingue',
      niveau : 8,
      continent: 'Ameriques',
      image: require('../Helpers/capital_images/saint-domingue.jpeg'),
   },
   {
      state: 'Dominique',
      prefixe: 'de la',
      capital: 'Roseau',
      niveau : 9,
      continent: 'Ameriques',
      image: require('../Helpers/capital_images/roseau.jpeg'),
   },
   {
      state: 'Italie',
      prefixe: 'de l’',
      capital: 'Rome',
      niveau : 0,
      continent: 'Europe',
      image: require('../Helpers/capital_images/rome.jpeg'),
   },
   {
      state: 'Arabie Saoudite',
      prefixe: 'de l’',
      capital: 'Riyad',
      niveau : 6,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/riyad.jpeg'),
   },
   {
      state: 'Lettonie',
      prefixe: 'de la',
      capital: 'Riga',
      niveau : 6,
      continent: 'Europe',
      image: require('../Helpers/capital_images/riga.jpeg'),
   },
   {
      state: 'Islande',
      prefixe: 'de l’',
      capital: 'Reykjavik',
      niveau : 7,
      continent: 'Europe',
      image: require('../Helpers/capital_images/reykjavik.jpeg'),
   },
   {
      state: 'Myanmar',
      prefixe: 'de',
      capital: 'Rangoon',
      niveau : 7,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/rangoon.jpeg'),
   },
   {
      state: 'Maroc',
      prefixe: 'du',
      capital: 'Rabat',
      niveau : 3,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/rabat.jpeg'),
   },
   {
      state: 'Equateur',
      prefixe: 'de l’',
      capital: 'Quito',
      niveau : 5,
      continent: 'Ameriques',
      image: require('../Helpers/capital_images/quito.jpeg'),
   },
   {
      state: 'Corée du Nord',
      prefixe: 'de la',
      capital: 'Pyongyang',
      niveau : 6,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/pyongyang.jpeg'),
   },
   {
      state: 'Afrique du sud',
      prefixe: 'de l’',
      capital: 'Prétoria',
      niveau : 7,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/pretoria.jpeg'),
   },
   {
      state: 'Cap Vert',
      prefixe: 'du',
      capital: 'Praïa',
      niveau : 8,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/praia.jpeg'),
   },
   {
      state: 'Rép. Tchèque',
      prefixe: 'de la',
      capital: 'Prague',
      niveau : 3,
      continent: 'Europe',
      image: require('../Helpers/capital_images/prague.jpeg'),
   },
   {
      state: 'Bénin',
      prefixe: 'du',
      capital: 'Porto Novo',
      niveau : 9,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/porto_novo.jpeg'),
   },
   {
      state: 'Maurice',
      prefixe: 'de',
      capital: 'Port-Louis',
      niveau : 10,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/port-louis.jpeg'),
   },
   {
      state: 'Haïti',
      prefixe: 'de',
      capital: 'Port-au-Prince',
      niveau : 9,
      continent: 'Ameriques',
      image: require('../Helpers/capital_images/port-au-prince.jpeg'),
   },
   {
      state: 'Trinidad et Tobago',
      prefixe: 'de',
      capital: 'Port d Espagne',
      niveau : 10,
      continent: 'Ameriques',
      image: require('../Helpers/capital_images/port_d_espagne.jpeg'),
   },
   {
      state: 'Cambodge',
      prefixe: 'du',
      capital: 'Phnom Penh',
      niveau : 6,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/phnom_penh.jpeg'),
   },
   {
      state: 'Chine',
      prefixe: 'de la',
      capital: 'Pékin',
      niveau : 0,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/pekin.jpeg'),
   },
   {
      state: 'France',
      prefixe: 'de la',
      capital: 'Paris',
      niveau : 0,
      continent: 'Europe',
      image: require('../Helpers/capital_images/paris.jpeg'),
   },
   {
      state: 'Surinam',
      prefixe: 'du',
      capital: 'Paramaribo',
      niveau : 9,
      continent: 'Ameriques',
      image: require('../Helpers/capital_images/paramaribo.jpeg'),
   },
   {
      state: 'Tahiti',
      prefixe: 'de',
      capital: 'Papeete',
      niveau : 6,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/papeete.jpeg'),
   },
   {
      state: 'Panama',
      prefixe: 'du',
      capital: 'Panama',
      niveau : 0,
      continent: 'Ameriques',
      image: require('../Helpers/capital_images/panama.jpeg'),
   },
   {
      state: 'Mongolie',
      prefixe: 'de la',
      capital: 'Oulan-Bator',
      niveau : 8,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/oulan-bator.jpeg'),
   },
   {
      state: 'Burkina Faso',
      prefixe: 'du',
      capital: 'Ouagadougou',
      niveau : 8,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/ouagadougou.jpeg'),
   },
   {
      state: 'Canada',
      prefixe: 'du',
      capital: 'Ottawa',
      niveau : 5,
      continent: 'Ameriques',
      image: require('../Helpers/capital_images/ottawa.jpeg'),
   },
   {
      state: 'Norvège',
      prefixe: 'de la',
      capital: 'Oslo',
      niveau : 3,
      continent: 'Europe',
      image: require('../Helpers/capital_images/oslo.jpeg'),
   },
   {
      state: 'Groenland',
      prefixe: 'du',
      capital: 'Nuuk',
      niveau : 10,
      continent: 'Europe',
      image: require('../Helpers/capital_images/nuuk.jpeg'),
   },
   {
      state: 'Tonga',
      prefixe: 'de',
      capital: 'Nuku Alofa',
      niveau : 10,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/nuku_alofa.jpeg'),
   },
   {
      state: 'Mauritanie',
      prefixe: 'de la',
      capital: 'Nouakchott',
      niveau : 8,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/nouakchott.jpeg'),
   },
   {
      state: 'Chypre',
      prefixe: 'de',
      capital: 'Nicosie',
      niveau : 5,
      continent: 'Europe',
      image: require('../Helpers/capital_images/nicosie.jpeg'),
   },
   {
      state: 'Niger',
      prefixe: 'du',
      capital: 'Niamey',
      niveau : 9,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/niamey.jpeg'),
   },
   {
      state: 'Inde',
      prefixe: 'de l’',
      capital: 'New Delhi',
      niveau : 1,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/new_delhi.jpeg'),
   },
   {
      state: 'Bahamas',
      prefixe: 'des',
      capital: 'Nassau',
      niveau : 4,
      continent: 'Ameriques',
      image: require('../Helpers/capital_images/nassau.jpeg'),
   },
   {
      state: 'Kénya',
      prefixe: 'du',
      capital: 'Nairobi',
      niveau : 4,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/nairobi.jpeg'),
   },
   {
      state: 'Tchad',
      prefixe: 'du',
      capital: 'N Djamena',
      niveau : 5,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/n_djamena.jpeg'),
   },
   {
      state: 'Russie',
      prefixe: 'de la',
      capital: 'Moscou',
      niveau : 0,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/moscou.jpeg'),
   },
   {
      state: 'Comores',
      prefixe: 'des',
      capital: 'Moroni',
      niveau : 10,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/moroni.jpeg'),
   },
   {
      state: 'Uruguay',
      prefixe: 'de l’',
      capital: 'Montevideo',
      niveau : 4,
      continent: 'Ameriques',
      image: require('../Helpers/capital_images/montevideo.jpeg'),
   },
   {
      state: 'Libéria',
      prefixe: 'de',
      capital: 'Monrovia',
      niveau : 9,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/monrovia.jpeg'),
   },
   {
      state: 'Monaco',
      prefixe: 'de',
      capital: 'Monaco',
      niveau : 3,
      continent: 'Europe',
      image: require('../Helpers/capital_images/monaco.jpeg'),
   },
   {
      state: 'Somalie',
      prefixe: 'de',
      capital: 'Mogadiscio',
      niveau : 5,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/mogadiscio.jpeg'),
   },
   {
      state: 'Biélorussie',
      prefixe: 'de',
      capital: 'Minsk',
      niveau : 6,
      continent: 'Europe',
      image: require('../Helpers/capital_images/minsk.jpeg'),
   },
   {
      state: 'Mexique',
      prefixe: 'du',
      capital: 'Mexico',
      niveau : 1,
      continent: 'Ameriques',
      image: require('../Helpers/capital_images/mexico.jpeg'),
   },
   {
      state: 'Swaziland',
      prefixe: 'de',
      capital: 'Mbabane',
      niveau : 10,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/mbabane.jpeg'),
   },
   {
      state: 'Lésotho',
      prefixe: 'du',
      capital: 'Maseru',
      niveau : 10,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/maseru.jpeg'),
   },
   {
      state: 'Oman',
      prefixe: 'd’',
      capital: 'Mascate',
      niveau : 9,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/mascate.jpeg'),
   },
   {
      state: 'Mozambique',
      prefixe: 'du',
      capital: 'Maputo',
      niveau : 10,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/maputo.jpeg'),
   },
   {
      state: 'Philippines',
      prefixe: 'des',
      capital: 'Manille',
      niveau : 3,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/manille.jpeg'),
   },
   {
      state: 'Bahreïn',
      prefixe: 'de',
      capital: 'Manama',
      niveau : 9,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/manama.jpeg'),
   },
   {
      state: 'Nicaragua',
      prefixe: 'de',
      capital: 'Managua',
      niveau : 8,
      continent: 'Ameriques',
      image: require('../Helpers/capital_images/managua.jpeg'),
   },
   {
      state: 'Maldives',
      prefixe: 'des',
      capital: 'Male',
      niveau : 10,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/male.jpeg'),
   },
   {
      state: 'Guinée Equatoriale',
      prefixe: 'de la',
      capital: 'Malabo',
      niveau : 10,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/malabo.jpeg'),
   },
   {
      state: 'Espagne',
      prefixe: 'de l’',
      capital: 'Madrid',
      niveau : 0,
      continent: 'Europe',
      image: require('../Helpers/capital_images/madrid.jpeg'),
   },
   {
      state: 'Luxembourg',
      prefixe: 'du',
      capital: 'Luxembourg',
      niveau : 0,
      continent: 'Europe',
      image: require('../Helpers/capital_images/luxembourg.jpeg'),
   },
   {
      state: 'Zambie',
      prefixe: 'de la',
      capital: 'Lusaka',
      niveau : 9,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/lusaka.jpeg'),
   },
   {
      state: 'Angola',
      prefixe: 'de l’',
      capital: 'Luanda',
      niveau : 8,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/luanda.jpeg'),
   },
   {
      state: 'Royaume-Uni',
      prefixe: 'du',
      capital: 'Londres',
      niveau : 0,
      continent: 'Europe',
      image: require('../Helpers/capital_images/londres.jpeg'),
   },
   {
      state: 'Togo',
      prefixe: 'du',
      capital: 'Lomé',
      niveau : 9,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/lome.jpeg'),
   },
   {
      state: 'Slovénie',
      prefixe: 'de la',
      capital: 'Ljubljana',
      niveau : 5,
      continent: 'Europe',
      image: require('../Helpers/capital_images/ljubljana.jpeg'),
   },
   {
      state: 'Portugal',
      prefixe: 'du',
      capital: 'Lisbonne',
      niveau : 1,
      continent: 'Europe',
      image: require('../Helpers/capital_images/lisbonne.jpeg'),
   },
   {
      state: 'Pérou',
      prefixe: 'du',
      capital: 'Lima',
      niveau : 3,
      continent: 'Ameriques',
      image: require('../Helpers/capital_images/lima.jpeg'),
   },
   {
      state: 'Malawi',
      prefixe: 'de',
      capital: 'Lilongwé',
      niveau : 10,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/lilongwe.jpeg'),
   },
   {
      state: 'Gabon',
      prefixe: 'du',
      capital: 'Libreville',
      niveau : 7,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/libreville.jpeg'),
   },
   {
      state: 'Egypte',
      prefixe: 'de l’',
      capital: 'Le Caire',
      niveau : 1,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/le_caire.jpeg'),
   },
   {
      state: 'Nigéria',
      prefixe: 'du',
      capital: 'Lagos',
      niveau : 8,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/lagos.jpeg'),
   },
   {
      state: 'Malte',
      prefixe: 'de',
      capital: 'La Vallette',
      niveau : 6,
      continent: 'Europe',
      image: require('../Helpers/capital_images/la_vallette.jpeg'),
   },
   {
      state: 'Bolivie',
      prefixe: 'de',
      capital: 'La Paz',
      niveau : 5,
      continent: 'Ameriques',
      image: require('../Helpers/capital_images/la_paz.jpeg'),
   },
   {
      state: 'Cuba',
      prefixe: 'de',
      capital: 'La Havane',
      niveau : 2,
      continent: 'Ameriques',
      image: require('../Helpers/capital_images/la_havane.jpeg'),
   },
   {
      state: 'Malaisie',
      prefixe: 'de',
      capital: 'Kuala Lumpur',
      niveau : 8,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/kuala_lumpur.jpeg'),
   },
   {
      state: 'Koweït',
      prefixe: 'du',
      capital: 'Koweït',
      niveau : 2,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/koweit.jpeg'),
   },
   {
      state: 'Rép. Dém. Congo',
      prefixe: 'de la',
      capital: 'Kinshasa',
      niveau : 4,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/kinshasa.jpeg'),
   },
   {
      state: 'Jamaïque',
      prefixe: 'de la',
      capital: 'Kingston',
      niveau : 8,
      continent: 'Ameriques',
      image: require('../Helpers/capital_images/kingston.jpeg'),
   },
   {
      state: 'Rwanda',
      prefixe: 'du',
      capital: 'Kigali',
      niveau : 6,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/kigali.jpeg'),
   },
   {
      state: 'Ukraine',
      prefixe: 'de l’',
      capital: 'Kiev',
      niveau : 6,
      continent: 'Europe',
      image: require('../Helpers/capital_images/kiev.jpeg'),
   },
   {
      state: 'Soudan',
      prefixe: 'du',
      capital: 'Khartoum',
      niveau : 5,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/khartoum.jpeg'),
   },
   {
      state: 'Népal',
      prefixe: 'du',
      capital: 'Katmandou',
      niveau : 6,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/katmandou.jpeg'),
   },
   {
      state: 'Ouganda',
      prefixe: 'de l’',
      capital: 'Kampala',
      niveau : 9,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/kampala.jpeg'),
   },
   {
      state: 'Afghanistan',
      prefixe: 'de l’',
      capital: 'Kaboul',
      niveau : 4,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/kaboul.jpeg'),
   },
   {
      state: 'Israël',
      prefixe: 'd’',
      capital: 'Jérusalem',
      niveau : 1,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/jerusalem.jpeg'),
   },
   {
      state: 'Indonésie',
      prefixe: 'de l’',
      capital: 'Jakarta',
      niveau : 8,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/jakarta.jpeg'),
   },
   {
      state: 'Pakistan',
      prefixe: 'du',
      capital: 'Islamabad',
      niveau : 7,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/islamabad.jpeg'),
   },
   {
      state: 'Finlande',
      prefixe: 'de',
      capital: 'Helsinki',
      niveau : 5,
      continent: 'Europe',
      image: require('../Helpers/capital_images/helsinki.jpeg'),
   },
   {
      state: 'Zimbabwé',
      prefixe: 'du',
      capital: 'Hararé',
      niveau : 10,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/harare.jpeg'),
   },
   {
      state: 'Vietnam',
      prefixe: 'du',
      capital: 'Hanoi',
      niveau : 3,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/hanoi.jpeg'),
   },
   {
      state: 'Guatémala',
      prefixe: 'de',
      capital: 'Guatémala',
      niveau : 2,
      continent: 'Ameriques',
      image: require('../Helpers/capital_images/guatemala.jpeg'),
   },
   {
      state: 'Guyana',
      prefixe: 'de',
      capital: 'Georgetown',
      niveau : 7,
      continent: 'Ameriques',
      image: require('../Helpers/capital_images/georgetown.jpeg'),
   },
   {
      state: 'Botswana',
      prefixe: 'du',
      capital: 'Gaborone',
      niveau : 9,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/gaborone.jpeg'),
   },
   {
      state: 'Sierra Léone',
      prefixe: 'de la',
      capital: 'Freetown',
      niveau : 8,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/freetown.jpeg'),
   },
   {
      state: 'Arménie',
      prefixe: 'de l’',
      capital: 'Erevan',
      niveau : 4,
      continent: 'Europe',
      image: require('../Helpers/capital_images/erevan.jpeg'),
   },
   {
      state: 'Irlande',
      prefixe: 'de l’',
      capital: 'Dublin',
      niveau : 1,
      continent: 'Europe',
      image: require('../Helpers/capital_images/dublin.jpeg'),
   },
   {
      state: 'Tadjikistan',
      prefixe: 'du',
      capital: 'Douchanbé',
      niveau : 9,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/douchanbe.jpeg'),
   },
   {
      state: 'Qatar',
      prefixe: 'du',
      capital: 'Doha',
      niveau : 7,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/doha.jpeg'),
   },
   {
      state: 'Tanzanie',
      prefixe: 'de',
      capital: 'Dodoma',
      niveau : 10,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/dodoma.jpeg'),
   },
   {
      state: 'Djibouti',
      prefixe: 'de',
      capital: 'Djibouti',
      niveau : 1,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/djibouti.jpeg'),
   },
   {
      state: 'Bangladesh',
      prefixe: 'du',
      capital: 'Dhaka',
      niveau : 8,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/dhaka.jpeg'),
   },
   {
      state: 'Syrie',
      prefixe: 'de',
      capital: 'Damas',
      niveau : 4,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/damas.jpeg'),
   },
   {
      state: 'Sénégal',
      prefixe: 'du',
      capital: 'Dakar',
      niveau : 2,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/dakar.jpeg'),
   },
   {
      state: 'Danemark',
      prefixe: 'du',
      capital: 'Copenhage',
      niveau : 2,
      continent: 'Europe',
      image: require('../Helpers/capital_images/copenhage.jpeg'),
   },
   {
      state: 'Guinée',
      prefixe: 'de',
      capital: 'Conakry',
      niveau : 7,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/conakry.jpeg'),
   },
   {
      state: 'Sri Lanka',
      prefixe: 'du',
      capital: 'Colombo',
      niveau : 7,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/colombo.jpeg'),
   },
   {
      state: 'Moldavie',
      prefixe: 'de',
      capital: 'Chisinau',
      niveau : 7,
      continent: 'Europe',
      image: require('../Helpers/capital_images/chisinau.jpeg'),
   },
   {
      state: 'Vénézuela',
      prefixe: 'du',
      capital: 'Caracas',
      niveau : 3,
      continent: 'Ameriques',
      image: require('../Helpers/capital_images/caracas.jpeg'),
   },
   {
      state: 'Australie',
      prefixe: 'de l’',
      capital: 'Canberra',
      niveau : 3,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/canberra.jpeg'),
   },
   {
      state: 'Burundi',
      prefixe: 'du',
      capital: 'Bujumbura',
      niveau : 9,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/bujumbura.jpeg'),
   },
   {
      state: 'Argentine',
      prefixe: 'de l’',
      capital: 'Buenos Aires',
      niveau : 1,
      continent: 'Ameriques',
      image: require('../Helpers/capital_images/buenos_aires.jpeg'),
   },
   {
      state: 'Hongrie',
      prefixe: 'de',
      capital: 'Budapest',
      niveau : 3,
      continent: 'Europe',
      image: require('../Helpers/capital_images/budapest.jpeg'),
   },
   {
      state: 'Roumanie',
      prefixe: 'de',
      capital: 'Bucarest',
      niveau : 5,
      continent: 'Europe',
      image: require('../Helpers/capital_images/bucarest.jpeg'),
   },
   {
      state: 'Belgique',
      prefixe: 'de',
      capital: 'Bruxelles',
      niveau : 1,
      continent: 'Europe',
      image: require('../Helpers/capital_images/bruxelles.jpeg'),
   },
   {
      state: 'Congo',
      prefixe: 'du',
      capital: 'Brazzaville',
      niveau : 4,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/brazzaville.jpeg'),
   },
   {
      state: 'Slovaquie',
      prefixe: 'de',
      capital: 'Bratislava',
      niveau : 6,
      continent: 'Europe',
      image: require('../Helpers/capital_images/bratislava.jpeg'),
   },
   {
      state: 'Brésil',
      prefixe: 'du',
      capital: 'Brasilia',
      niveau : 2,
      continent: 'Ameriques',
      image: require('../Helpers/capital_images/brasilia.jpeg'),
   },
   {
      state: 'Colombie',
      prefixe: 'de',
      capital: 'Bogota',
      niveau : 5,
      continent: 'Ameriques',
      image: require('../Helpers/capital_images/bogota.jpeg'),
   },
   {
      state: 'Guinée Bissau',
      prefixe: 'de',
      capital: 'Bissao',
      niveau : 9,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/bissao.jpeg'),
   },
   {
      state: 'Kirghizstan',
      prefixe: 'du',
      capital: 'Bichkek',
      niveau : 9,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/bichkek.jpeg'),
   },
   {
      state: 'Liban',
      prefixe: 'du',
      capital: 'Beyrouth',
      niveau : 2,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/beyrouth.jpeg'),
   },
   {
      state: 'Suisse',
      prefixe: 'de',
      capital: 'Berne',
      niveau : 2,
      continent: 'Europe',
      image: require('../Helpers/capital_images/berne.jpeg'),
   },
   {
      state: 'Allemagne',
      prefixe: 'de l’',
      capital: 'Berlin',
      niveau : 1,
      continent: 'Europe',
      image: require('../Helpers/capital_images/berlin.jpeg'),
   },
   {
      state: 'Bélize',
      prefixe: 'de',
      capital: 'Belmopan',
      niveau : 8,
      continent: 'Ameriques',
      image: require('../Helpers/capital_images/belmopan.jpeg'),
   },
   {
      state: 'Serbie',
      prefixe: 'de la',
      capital: 'Belgrade',
      niveau : 5,
      continent: 'Europe',
      image: require('../Helpers/capital_images/belgrade.jpeg'),
   },
   {
      state: 'Gambie',
      prefixe: 'de',
      capital: 'Banjul',
      niveau : 8,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/banjul.jpeg'),
   },
   {
      state: 'Centre-Afrique',
      prefixe: 'de',
      capital: 'Bangui',
      niveau : 6,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/bangui.jpeg'),
   },
   {
      state: 'Thaïlande',
      prefixe: 'de',
      capital: 'Bangkok',
      niveau : 3,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/bangkok.jpeg'),
   },
   {
      state: 'Mali',
      prefixe: 'du',
      capital: 'Bamako',
      niveau : 3,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/bamako.jpeg'),
   },
   {
      state: 'Azerbaïdjan',
      prefixe: 'de l’',
      capital: 'Bakou',
      niveau : 8,
      continent: 'Europe',
      image: require('../Helpers/capital_images/bakou.jpeg'),
   },
   {
      state: 'Irak',
      prefixe: 'de l’',
      capital: 'Bagdad',
      niveau : 5,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/bagdad.jpeg'),
   },
   {
      state: 'Grèce',
      prefixe: 'de',
      capital: 'Athènes',
      niveau : 1,
      continent: 'Europe',
      image: require('../Helpers/capital_images/athenes.jpeg'),
   },
   {
      state: 'Paraguay',
      prefixe: 'du',
      capital: 'Asuncion',
      niveau : 7,
      continent: 'Ameriques',
      image: require('../Helpers/capital_images/asuncion.jpeg'),
   },
   {
      state: 'Erythrée',
      prefixe: 'de l’',
      capital: 'Asmera',
      niveau : 10,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/asmera.jpeg'),
   },
   {
      state: 'Madagascar',
      prefixe: 'de',
      capital: 'Antananarivo',
      niveau : 4,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/antananarivo.jpeg'),
   },
   {
      state: 'Turquie',
      prefixe: 'de',
      capital: 'Ankara',
      niveau : 2,
      continent: 'Europe',
      image: require('../Helpers/capital_images/ankara.jpeg'),
   },
   {
      state: 'Pays-Bas',
      prefixe: 'des',
      capital: 'Amsterdam',
      niveau : 2,
      continent: 'Europe',
      image: require('../Helpers/capital_images/amsterdam.jpeg'),
   },
   {
      state: 'Jordanie',
      prefixe: 'de',
      capital: 'Amman',
      niveau : 7,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/amman.jpeg'),
   },
   {
      state: 'Kazakhstan',
      prefixe: 'du',
      capital: 'Alma-Ata',
      niveau : 10,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/alma-ata.jpeg'),
   },
   {
      state: 'Algérie',
      prefixe: 'de l’',
      capital: 'Alger',
      niveau : 0,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/alger.jpeg'),
   },
   {
      state: 'Ethiopie',
      prefixe: 'de l’',
      capital: 'Addis-Abéba',
      niveau : 7,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/addis-abeba.jpeg'),
   },
   {
      state: 'Turkménistan',
      prefixe: 'du',
      capital: 'Achkhabad',
      niveau : 9,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/achkhabad.jpeg'),
   },
   {
      state: 'Ghana',
      prefixe: 'du',
      capital: 'Accra',
      niveau : 10,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/accra.jpeg'),
   },
   {
      state: 'Emirats Arabes Unis',
      prefixe: 'des',
      capital: 'Abu Dhabi',
      niveau : 5,
      continent: 'AsiePacif',
      image: require('../Helpers/capital_images/abu_dhabi.jpeg'),
   },
   {
      state: 'Côte d Ivoire',
      prefixe: 'de',
      capital: 'Abidjan',
      niveau : 3,
      continent: 'Afrique',
      image: require('../Helpers/capital_images/abidjan.jpeg'),
   },
]